#!/usr/bin/env python
"""Adds a genuinely new domain to training: short/medium business-register
text, which MAGE never contains a single example of (its 10 domains are
Reddit writing-prompt fiction, Yelp reviews, news/XSum, TL;DR, SQuAD QA, ROC
stories, sci_gen, plus the GPT-4-extension's cnn/dialogsum/imdb/pubmed --
none of them casual professional writing). This is the fix the earlier
short-text-truncation augmentation could NOT provide: truncating existing
MAGE documents only ever produces shorter spans of the SAME domains, never a
genuinely new register. Confirmed on a real example: a short human sentence
about quarterly revenue reporting scored 93-95% machine both before and after
that truncation-only augmentation.

Human side: real Enron ham (non-spam) emails -- genuine human business
correspondence, public dataset, free.
Machine side: business-register text generated by a real modern LLM (Groq-
hosted Llama 3.3 70B) across varied prompts (emails, memos, status updates,
short reports) -- not MAGE's older generators, so this also broadens
generator diversity in a register that matters.

Appends to whatever data/processed/train.parquet currently contains (the
short-text + paraphrase augmented set from the previous round) rather than
starting over, since that round's other gains (RAID robustness, GPT-4-unseen
slice) were real and worth keeping.
"""
from __future__ import annotations

import os
import random
import shutil
import time

import pandas as pd
import requests
from datasets import load_dataset

from forensics.config import PROCESSED_DIR, SEED

N_HUMAN_ENRON = 3500
N_MACHINE_BUSINESS = 3500
MIN_WORDS, MAX_WORDS = 15, 150
GROQ_MODEL = "llama-3.3-70b-versatile"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
CHECKPOINT_EVERY = 200

PROMPT_TEMPLATES = [
    "Write a short professional email (3-5 sentences) to a colleague about {topic}. No subject line, just the email body.",
    "Write a brief internal business memo (3-5 sentences) about {topic}.",
    "Write a short status update (3-5 sentences) for a work project related to {topic}.",
    "Write a short, casual Slack-style message to a coworker about {topic}.",
    "Write 3-5 sentences of commentary on quarterly or financial reporting related to {topic}.",
]
TOPICS = [
    "a delayed shipment", "quarterly revenue numbers", "a client meeting rescheduling",
    "a budget overrun", "a new hire starting next week", "a server outage last night",
    "vendor contract renewal", "an upcoming audit", "office relocation plans",
    "a marketing campaign's performance", "headcount planning for next year",
    "a pricing change for customers", "an internal policy update", "a product launch delay",
    "expense report approvals", "a customer complaint escalation", "team offsite planning",
    "year-end inventory counts", "a compliance training deadline", "a merger rumor",
]


def _fetch_enron_human_rows(n: int, seed: int) -> pd.DataFrame:
    ds = load_dataset("SetFit/enron_spam", split="train", streaming=True)
    rng = random.Random(seed)
    rows = []
    seen_texts = set()
    for row in ds:
        if row["label_text"] != "ham":
            continue
        text = row["message"].strip()
        n_words = len(text.split())
        if not (MIN_WORDS <= n_words <= MAX_WORDS):
            continue
        if text in seen_texts:
            continue
        seen_texts.add(text)
        rows.append({"text": text, "is_machine": 0})
        if len(rows) >= n:
            break
    rng.shuffle(rows)
    return pd.DataFrame(rows)


def _groq_generate(key: str, prompt: str, max_retries: int = 5) -> str | None:
    for attempt in range(max_retries):
        try:
            resp = requests.post(
                GROQ_URL,
                # Connection: close forces a fresh TCP connection every call --
                # a run left overnight hit a connection stuck in CLOSE_WAIT
                # (very likely a network blip/sleep) that requests' default
                # keep-alive pooling then kept trying to reuse, hanging the
                # process for hours with no exception ever raised despite the
                # timeout below. A fresh connection per call costs a little
                # latency but can't get stuck on a dead reused socket.
                headers={"Authorization": f"Bearer {key}", "Connection": "close"},
                json={
                    "model": GROQ_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "max_tokens": 200,
                    "temperature": 1.0,
                },
                timeout=(10, 30),
            )
            if resp.status_code == 429:
                # A daily-quota 429 ("tokens per day") won't clear on any
                # retry-backoff timescale -- retrying it is what actually
                # caused the "hang" this whole pipeline hit in practice (5
                # retries x up to 30s, repeated forever, per prompt, with
                # nothing printed since 429s never reach the except branch
                # below). Fail the whole run immediately instead.
                if "tokens per day" in resp.text.lower() or "TPD" in resp.text:
                    raise RuntimeError(f"Groq daily token quota exhausted: {resp.text[:300]}")
                time.sleep(min(2 ** attempt, 30))
                continue
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"].strip()
        except requests.RequestException:
            if attempt == max_retries - 1:
                return None
            time.sleep(min(2 ** attempt, 30))
    return None


# Free-tier Groq cap on this key measured directly (429 body): 30 requests/min
# for this model. 2.1s between requests keeps steady state just under that
# (~28.6/min) instead of firing as fast as possible and eating repeated 429s
# -- each 429 wastes its retry-after wait without producing a row, which is
# why the un-paced version made only 200 rows in 15 minutes instead of the
# ~30/min = 450 the limit actually allows.
REQUEST_INTERVAL_SECONDS = 2.1


def _generate_business_rows(n: int, seed: int) -> pd.DataFrame:
    key = os.environ.get("GROQ_API_KEY")
    if not key:
        raise RuntimeError("GROQ_API_KEY not set in environment")

    rng = random.Random(seed)
    checkpoint_path = PROCESSED_DIR / "groq_business_augment.partial.parquet"
    rows: list[dict] = []
    if checkpoint_path.exists():
        rows = pd.read_parquet(checkpoint_path).to_dict("records")
        print(f"Resuming Groq generation from {len(rows)}/{n}", flush=True)

    while len(rows) < n:
        t0 = time.time()
        template = rng.choice(PROMPT_TEMPLATES)
        topic = rng.choice(TOPICS)
        prompt = template.format(topic=topic)
        text = _groq_generate(key, prompt)
        if text:
            rows.append({"text": text, "is_machine": 1})
        if len(rows) % CHECKPOINT_EVERY == 0:
            pd.DataFrame(rows).to_parquet(checkpoint_path, index=False)
            print(f"  generated {len(rows)}/{n}", flush=True)
        elapsed = time.time() - t0
        if elapsed < REQUEST_INTERVAL_SECONDS:
            time.sleep(REQUEST_INTERVAL_SECONDS - elapsed)

    pd.DataFrame(rows).to_parquet(checkpoint_path, index=False)
    return pd.DataFrame(rows[:n])


def main():
    train_path = PROCESSED_DIR / "train.parquet"
    backup_path = PROCESSED_DIR / "train_pre_domain_augment_snapshot.parquet"
    if not backup_path.exists():
        shutil.copy2(train_path, backup_path)
        print(f"Snapshotted current train set to {backup_path}", flush=True)
    else:
        print(f"Snapshot already exists at {backup_path}, not overwriting", flush=True)

    current_df = pd.read_parquet(backup_path)
    print(f"Current training rows: {len(current_df)}", flush=True)

    print("\n=== Fetching Enron human (ham) email rows ===", flush=True)
    enron_df = _fetch_enron_human_rows(N_HUMAN_ENRON, seed=SEED)
    print(f"Enron human rows: {len(enron_df)}", flush=True)

    print("\n=== Generating Groq business-register machine rows ===", flush=True)
    groq_df = _generate_business_rows(N_MACHINE_BUSINESS, seed=SEED)
    print(f"Groq machine rows: {len(groq_df)}", flush=True)

    combined = pd.concat(
        [current_df[["text", "is_machine"]], enron_df, groq_df], ignore_index=True
    )
    print(f"\nCombined training rows: {len(combined)} "
          f"(prior {len(current_df)} + enron {len(enron_df)} + groq {len(groq_df)})", flush=True)

    combined.to_parquet(train_path, index=False)
    print(f"Wrote domain-augmented training set to {train_path}", flush=True)


if __name__ == "__main__":
    main()
